# -*- coding: utf-8 -*-
"""1WA24CS085_week1_tictactoe_vacuumcleaner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5FicMfUN_0QC2giM4MADl-rd5IYgxIj
"""

def reflex_vacuum_agent(location, status):
    if status == 'Dirty':
        return 'Pick the Dirt'
    elif location == 'A':
        return 'Right'
    elif location == 'B':
        return 'Left'

if __name__ == "__main__":
    test_states = [
        ('A', 'Dirty'),
        ('A', 'Clean'),
        ('B', 'Dirty'),
        ('B', 'Clean')]

    for loc, stat in test_states:
        action = reflex_vacuum_agent(loc, stat)
        print(f"Location: {loc} | Status: {stat} ---> Action: {action}")
print("NAME-BIKASHITA SAHA")
print("USN-1WA24CS085")

# The board positions are indexed from 0 to 8:
# 0 | 1 | 2
# ---------
# 3 | 4 | 5
# ---------
# 6 | 7 | 8

# 1. Set up the initial board layout with your conditions
board = [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
board[2], board[3], board[6] = 'X', 'X', 'X'
board[0], board[7], board[8] = 'O', 'O', 'O'

# Initialize path costs (3 moves have already been made by both players)
path_cost = {'X': 3, 'O': 3}
turn = 'X'

# 2. Main Game Loop
while True:
    # Print the current board layout and current path costs
    print(f"\n {board[0]} | {board[1]} | {board[2]} ")
    print("-----------")
    print(f" {board[3]} | {board[4]} | {board[5]} ")
    print("-----------")
    print(f" {board[6]} | {board[7]} | {board[8]} \n")
    print(f"Current Path Cost -> X: {path_cost['X']}, O: {path_cost['O']}")

    # Check for a winner (Rows, Columns, Diagonals)
    win_lines = [(0,1,2), (3,4,5), (6,7,8), (0,3,6), (1,4,7), (2,5,8), (0,4,8), (2,4,6)]
    winner = None
    for a, b, c in win_lines:
        if board[a] == board[b] == board[c] != ' ':
            winner = board[a]

    if winner:
        print(f"\nPlayer {winner} wins! Total path cost for {winner}: {path_cost[winner]}")
        break
    elif ' ' not in board:
        print("\nIt's a tie!")
        break

    # Get the player's move
    try:
        move = int(input(f"\nPlayer {turn}, choose an empty cell (0-8): "))
        if move < 0 or move > 8 or board[move] != ' ':
            print("Invalid move! The cell is either taken or out of range. Try again.")
            continue
    except (ValueError, IndexError):
        print("Please enter a valid number between 0 and 8.")
        continue

    # Make the move, add +1 to the player's path cost, and switch turns
    board[move] = turn
    path_cost[turn] += 1
    turn = 'O' if turn == 'X' else 'X'
print("NAME- BIKASHITA SAHA")
print("USN- 1WA24CS085")